[package]
name = "epicycles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
euclid = "0.22.7"
image = "0.24.4"
structopt = "0.3"
